# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-24 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_tweet_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=200, validators=[tweets.validators.validate_content]),
        ),
    ]
