# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-31 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0013_auto_20170524_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
